### PR TITLE
Filter by pipelines

### PR DESCRIPTION
**Pull request by thefeqy**
I just added a new method without removing anything, `filter` is a method that I added to the `model.stub` that handles the same search filtration in just a short and much easier code for the package users.
> This is my first PR, so if you have any feedback, please let me know

### CODE REVIEW

**Comment by Mahmoud-Italy** [comment]
Well, Thank you for your effort
That's might be cool idea
Just let me test it first then I'll get back to you

**Comment by thefeqy** [comment]
take your time, just let me know anything new and keep me up to date, thank you

**Comment by Mahmoud-Italy** [comment]
Hey, I'm sorry for being late,
But I've admired that's brilliant.

**Comment by thefeqy** [comment]
Thank you, my pleasure

**Pull request merged**
